// Package user is an implementation of [user] service generated by goa design
package user

import (
	"context"

	genUser "github.com/oleshko-g/oggophermart/internal/gen/user"
	"github.com/oleshko-g/oggophermart/internal/service/errors"
)

// user service example implementation.
// The example methods slog the requests and return zero values.
type userSvc struct{}

var _ genUser.Service = (*userSvc)(nil)

// NewUser returns the user service implementation.
func NewUser() genUser.Service {
	return &userSvc{}
}

// Register implements register.
func (s *userSvc) Register(ctx context.Context, p *genUser.LoginPass) (res *genUser.UserServiceResult, err error) {
	return nil, errors.NotImplemented
}

// Login implements login.
func (s *userSvc) Login(ctx context.Context, p *genUser.LoginPass) (res *genUser.UserServiceResult, err error) {
	return nil, errors.NotImplemented
}
