// Package user is an implementation of [user] service generated by goa design
package user

import (
	"context"
	"errors"
	"fmt"
	"time"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	genSvc "github.com/oleshko-g/oggophermart/internal/gen/service"
	genUser "github.com/oleshko-g/oggophermart/internal/gen/user"
	svcErrors "github.com/oleshko-g/oggophermart/internal/service/errors"
	"github.com/oleshko-g/oggophermart/internal/storage"
	storageErrors "github.com/oleshko-g/oggophermart/internal/storage/errors"
	"goa.design/goa/v3/security"
	"golang.org/x/crypto/bcrypt"
)

// user service example implementation.
// The example methods slog the requests and return zero values.
type userSvc struct {
	storage.User
	*Config
}

var _ genUser.Service = (*userSvc)(nil)

// New returns the user service implementation.
func New(cfg *Config, storage storage.User) *userSvc {
	return &userSvc{
		Config: cfg,
		User:   storage,
	}
}

// Register implements register.
func (s *userSvc) Register(ctx context.Context, p *genUser.LoginPassword) (authToken *genSvc.JWTToken, err error) {

	hashedPassword, err := hashPassword(p.Password)
	if err != nil {
		return &genSvc.JWTToken{}, svcErrors.ErrInternalServiceError
	}

	err = s.User.StoreUser(ctx, p.Login, hashedPassword)
	if err != nil {
		if errors.Is(err, storageErrors.ErrAlreadyExists) {
			return &genSvc.JWTToken{}, ErrLoginTaken
		}
		return &genSvc.JWTToken{}, svcErrors.ErrInternalServiceError
	}

	jwt, err := signUserJWT(p.Login, s.secretKey.String(), 1*time.Hour)
	if err != nil {
		return &genSvc.JWTToken{}, svcErrors.ErrInternalServiceError
	}

	return &genSvc.JWTToken{
		AuthToken: jwt,
	}, nil
}

// Login implements login.
func (s *userSvc) Login(ctx context.Context, p *genUser.LoginPassword) (authToken *genSvc.JWTToken, err error) {
	return &genSvc.JWTToken{}, svcErrors.ErrNotImplemented
}

func hashPassword(password string) (string, error) {

	hashedPasswordData, errHash := bcrypt.GenerateFromPassword([]byte(password), 0)
	if errHash != nil {
		return "", errHash
	}

	return string(hashedPasswordData), nil
}

func checkPasswordHash(hashedPassword, password string) error {
	return bcrypt.CompareHashAndPassword([]byte(hashedPassword), []byte(password))
}

func signUserJWT(login string, jwtSecret string, expiresIn time.Duration) (string, error) {
	t := jwt.NewWithClaims(jwt.SigningMethodHS256,
		jwt.RegisteredClaims{
			Issuer:    "oggophermart",
			IssuedAt:  jwt.NewNumericDate(time.Now().UTC()),
			ExpiresAt: jwt.NewNumericDate(time.Now().UTC().Add(expiresIn)),
			Subject:   login,
		},
	)
	return t.SignedString([]byte(jwtSecret))
}

func (s *userSvc) JWTAuth(ctx context.Context, token string, _ *security.JWTScheme) (context.Context, error) {
	userID, err := s.authenticate(ctx, token)
	if err != nil {
		return nil, err
	}
	return s.ContextWithUserID(ctx, userID), nil
}

func (s *userSvc) ContextWithUserID(ctx context.Context, userID uuid.UUID) context.Context {
	return context.WithValue(ctx, contextKeyUserID, userID)
}
func (s *userSvc) UserIDFromContext(ctx context.Context) (userID uuid.UUID, err error) {
	v := ctx.Value(contextKeyUserID)
	if v, ok := v.(uuid.UUID); ok {
		return v, nil
	}
	return uuid.UUID{}, svcErrors.ErrUserIsNotAuthenticated
}

func (s *userSvc) authenticate(ctx context.Context, token string) (userID uuid.UUID, err error) {
	claims := jwt.RegisteredClaims{}
	userJWT, err := jwt.ParseWithClaims(token, &claims,
		func(token *jwt.Token) (interface{}, error) {
			if token.Method.Alg() != jwt.SigningMethodHS256.Alg() {
				return nil, fmt.Errorf("error signing method must be HS256. Token's method is %s", token.Method.Alg())
			}
			return []byte(s.secretKey.String()), nil
		},
	)
	if err != nil {
		return uuid.UUID{}, err
	}
	login, err := userJWT.Claims.GetSubject()
	if err != nil {
		return uuid.UUID{}, err
	}

	userID, err = s.RetrieveUser(ctx, login)
	if err != nil {
		return uuid.UUID{}, err
	}

	return userID, nil
}

type contextKey int

const (
	contextKeyUserID contextKey = iota
)
