// Package balance is an implementation of [genBalance] service generated by goa design
package balance

import (
	"context"

	genBalance "github.com/oleshko-g/oggophermart/internal/gen/balance"
	"github.com/oleshko-g/oggophermart/internal/service/errors"
	"github.com/oleshko-g/oggophermart/internal/storage"
	"goa.design/goa/v3/security"
)

// balance service example implementation.
// The example methods log the requests and return zero values.
type balanceSvc struct{}

var _ genBalance.Service = (*balanceSvc)(nil)
var _ genBalance.Auther = (*balanceSvc)(nil)

// New returns the balance service implementation.
func New(storage storage.Balance) *balanceSvc {
	// TODO: connect to the storage
	return &balanceSvc{}
}

// PostOrder implements post order.
func (s *balanceSvc) UploadUserOrder(ctx context.Context, payload *genBalance.UploadUserOrderPayload) (res *genBalance.UploadUserOrderResult, err error) {
	return nil, errors.ErrNotImplemented
}

// JWTAuth is the implementation of [Auther]
// TODO: write JWTAuth
func (s *balanceSvc) JWTAuth(ctx context.Context, JWTToken string, schema *security.JWTScheme) (context.Context, error) {
	// TODO: call user service to authenticate token
	return nil, nil
}
